name: Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run benchmarks
      run: python benchmarks/throughput.py
